### PR TITLE
Update methods

### PR DESCRIPTION
**Pull request by filipemacedo**
Pre-defined color methods are great for saving time and maintaining a pattern, but we do not always want to display the name of the warning (success, error, information or warning), sometimes we want to use the default color but with a custom title .

A very important point is the need to pass the name of the bot every time we call the method, also put predefined (passing in the constructor) with the possibility of by a custom name from the method.

### CODE REVIEW

**Comment by jos-b** [comment]
I'm not sure I want to do this. I think that these methods are hellish enough already and adding complexity to them is just making them not backward compatible.

I am not opposed to adding the colours used to a constant in the MessageBuilder so people can select colours using that.

If you want to add the constants then revert changes on the main file and change builder.js to have a set of constants. Default name is a good idea but I'll add that myself after this because I've got a different way of implementing it.

**Comment by jos-b** [comment]
Also GitHub Actions has frozen again so I'll have to manually test when you are ready.

**Comment by filipemacedo** [comment]
No problem, really this action would be incompatible with the API, so it would be an update in the major version, depending on whether it would be more interesting to add new methods with the custom suffix.

Because the idea in this case is to just enjoy the color and be required to only pass the message or a personalized title

**Comment by jos-b** [comment]
I think we should work on extending the MessageBuilder, that is where I want focus to go from now, since it's the nicer replacement for the methods.

**Comment by filipemacedo** [comment]
I'll see later if I can do anything.

**Comment by jos-b** [comment]
Why was this closed?

**Comment by filipemacedo** [comment]
It was unintentionally, but I did it in a new way, coming home I raise the pull request.

**Pull request closed without merging**
