### PR TITLE
Added option to use the no wait feature of discord webhook

### PR DESCRIPTION
**Pull request by mjrider**

### CODE REVIEW

**Comment by jos-b** [comment]
Never heard of this. What is the nowait feature?

**Comment by mjrider** [comment]
https://discordapp.com/developers/docs/resources/webhook#execute-slackcompatible-webhook

waits for server confirmation of message send before response (defaults to true; when false a message that is not saved does not return an error)

**Comment by jos-b** [comment]
Ah okay, sounds good, cheers.

**Comment by jos-b** [comment]
I'll push this out in the next release

**Comment by jos-b** [comment]
In fact, due to my little brainstorming session in #19, I've just pushed this as version v2.4.0

**Pull request merged**
