### PR TITLE
Adds async await to all of the times this.sendPayload is used.

### PR DESCRIPTION
**Pull request by aarmora**
Without the async await, it seems that this will cause it to hang if in the middle of loops or other things? I'm not exactly sure except that I have one script that it causes to fail every time and other scripts that have never had a problem (that I've noticed).

This seems to resolve the issue.

Thanks for the great package, by the way!

### CODE REVIEW

**Comment by jos-b** [comment]
Could you provide the script? I can't seem to replicate this locally.

I do need to do some work on what these functions return because it is rather inconsistent right now iirc.

**Comment by aarmora** [comment]
I'm trying to reproduce it more consistently now. I'm pretty sure there
will be funky behavior without those awaits but let's hold on going forward
with the PR until I get something more reliable.

Thanks!

Jordan

**Comment by aarmora** [comment]
Okay, I have something. It seems like throwing another promise in there ends it after rate limiting starts. I'm not sure why yet. Still digging.

```
const hook = new Webhook(<url>);

const otherAttempts = ['a', 'b', 'c'];

const attempts = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

(async () => {


    for (let attempt of attempts) {
        await promiseFunction();
        for (let otherAttempt of otherAttempts) {
            console.log('before', attempt, otherAttempt);
            await hook.success('name', `${attempt} ${otherAttempt}`);
            console.log('after', attempt, otherAttempt);
        }
    }
})();

function promiseFunction() {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('in ze promise function');
            resolve();
        }, 750);
    });
}
```

**Comment by jos-b** [comment]
Okay, so when I decrease the duration you chose to 250ms I can reproduce this and I think I know why. I also think I have a possible solution to this issue. Let me experiment and get back to you.

**Comment by jos-b** [comment]
Okay! I think I fixed it. I'll go over what was happening.

```
- inside promise function
- hook is called and is returned a rate limit by discord
- setTimeout executes a new promise which is resolved when the Webhooks goes through but it does not resolve the parent promise
- parent promise is never resolved so it is blocked and never resolved.
```

To fix this I have added a parameter called `resolveFunction` to the sendPayload function, this means that when the webhook is rate limited it still resolves all outer promises which means no blocking.

**Comment by jos-b** [comment]
This is the solution I came up with
image
could you test this code with your example and see if things work:
```js
    sendPayload(payload, resolveFunction) {
        this.verifyName(payload.username);
        if (this.ready) {
            return new Promise((resolve, reject) => {
                snekfetch.post(this.endpoint)
                    .send(payload)
                    .then(() => {
                        if (resolveFunction) {
                            resolveFunction();
                        }

                        resolve();
                    })
                    .catch((err) => {
                        let e = JSON.parse(err.text);
                        if (e.retry_after) { // We are being ratelimited
                            setTimeout(() => {
                                this.sendPayload(payload, resolve);
                            }, e.retry_after);
                        } else {
                            reject(err);
                        }
                    });
            });
        } else {
            setTimeout(() => {
                this.sendPayload(payload);
            }, 10);
        }
    }
```

**Comment by aarmora** [comment]
Okay, so I've spent quite a bit of time testing this. It's definitely significantly better but it still seems to be just stopping the script eventually. My main script where I first noticed it is pretty extensive and can run for hours and so it was hard to tell if it was failing due to this or some other reason.

Finally, I tested more on my sample script and was able to reproduce it consistently. I bumped up one of the arrays from 10 to 30 and it only completed once out of about 30 times.

`[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30];`

**Comment by jos-b** [comment]
Using your test code and upping the array to 30 I get a block at 11, this isn't a code thing though it is doing what is expected.

```js
in ze promise function
before 11 a
{ global: false,
  message: 'You are being rate limited.',
  retry_after: 46382 }
```
As you can see before 11 a we were rate limited. There must be some sort of higher rate limit every 30 messages or something (considering we send 3 per number and it stops at 11). After 46 seconds I was able to send stuff again and it resumed. Then at 21a it stopped again
```
before 21 a
{ global: false,
  message: 'You are being rate limited.',
  retry_after: 46456 }
```
so I think that the stopping is just rate limits.

**Comment by jos-b** [comment]
If you want to test this out in a Discord server with me I've got [this development one](https://discord.gg/avdCtS) where I've been testing the webhooks today.

**Comment by aarmora** [comment]
@jos-b I see the long pauses (45+ seconds) but it'll eventually just end for me. The script just stops. Does it complete to 30 for you every time, even while waiting?

**Comment by aarmora** [comment]
Odd...it's failing for me almost every time.

screenshot_20

Your code looks like the following?

```
const hook = new Webhook('https://discordapp.com/api/webhooks/531203290755760148/zvp_lglHNldw2l6Qj9mrdA9bwMpiuttCPg-S777JM9qsLtDxomYrcx6CN_aEMdYlLGVc');

const otherAttempts = ['a', 'b', 'c'];

const attempts = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30];

(async () => {


    for (let attempt of attempts) {
        await promiseFunction();
        for (let otherAttempt of otherAttempts) {
            console.log('before', attempt, otherAttempt);
            await hook.success('name', `${attempt} `);
            console.log('inside', attempt, otherAttempt);
            console.log('after', attempt, otherAttempt);
        }
    }
})();

function promiseFunction() {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('in ze promise function');
            resolve();
        }, 250);
    });
}
```

**Comment by aarmora** [comment]
And this is my sendPayload function:

```
    /**
    @param {object} payload The payload to send.
    */
    sendPayload(payload, resolveFunction) {
        this.verifyName(payload.username);
        if (this.ready) {
            return new Promise((resolve, reject) => {
                snekfetch.post(this.endpoint)
                    .send(payload)
                    .then(() => {
                        if (resolveFunction) {
                            resolveFunction();
                        }

                        resolve();
                    })
                    .catch((err) => {
                        let e = JSON.parse(err.text);
                        console.log('error', e);
                        if (e.retry_after) { // We are being ratelimited
                            setTimeout(() => {
                                this.sendPayload(payload, resolve);
                            }, e.retry_after);
                        } else {
                            reject(err);
                        }
                    });
            });
        } else {
            setTimeout(() => {
                this.sendPayload(payload);
            }, 10);
        }
    }
```

**Comment by jos-b** [comment]
```js
const {Webhook} = require(".")

const hook = new Webhook("url")

const otherAttempts = ['a', 'b', 'c'];

const attempts = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30];

(async () => {


    for (let attempt of attempts) {
        await promiseFunction();
        for (let otherAttempt of otherAttempts) {
            console.log('before', attempt, otherAttempt);
            await hook.success('name', `${attempt} ${otherAttempt}`);
            console.log('after', attempt, otherAttempt);
        }
    }
})();

function promiseFunction() {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('in ze promise function');
            resolve();
        }, 250);
    });
}
```
this is my code

**Comment by jos-b** [comment]
Are you manually stopping the program or is it automatically exiting?

**Comment by aarmora** [comment]
It's automatically exiting. I wonder what's up with my code that it's breaking and yours is not.

**Comment by jos-b** [comment]
That's really weird, if it matters at all I'm running this on MacOS Mojave. There are no calls to anything that would cause the program to exit though. Do you happen to know the exit code? (I forgot if that is a thing on windows?)

**Comment by jos-b** [comment]
Looks to be related 
image

Run `echo %ERRORLEVEL%` after the program exits to find the exit code.

**Comment by jos-b** [comment]
Ah right, forgot that you were using a bash thing. That's really odd. I wonder if there is some weird node thing I'm missing here...

**Comment by aarmora** [comment]
I just tested further on my main script and it worked for a long time but eventually did just stop after a `retry_after`. My main script is on an ubuntu web server so it's not related to windows. It's noteworthy that it didn't exit the script, just hung there. I took two screen shots with time stamps so you can see that it's not just waiting for the `retry_after`.

At this point though, I'd say you've done enough for me! My case is pretty rare, only when someone is really, consistently spamming webhooks apparently? I'll probably just be a bit more creative with how I push the hook.

screenshot_21
screenshot_22

**Comment by jos-b** [comment]
Sorry I couldn’t resolve the this, I’m equally as confused! Since this PR doesnt exactly resolve the problems shown I’ll close it and push the fix that resolved unreturned promises when I get on my laptop. I think that this is a weird enough scenario to call it an edge case (though if it does arise from normal operation do let me know).

Thank you for raising this issue with me and for helping make this library better!

**Comment by jos-b** [comment]
Okay, released in version [v3.0.3](https://www.npmjs.com/package/webhook-discord/v/3.0.3) to NPM. Rate-limiting should now play nice :ok_hand:.

**Pull request closed without merging**
